destroy building
dobschal/castles-2025 pull request #1
Opened 2024-11-02 09:00 UTC by markusdent

Can't create draft PR...

Tests and frontend changes will follow in the next couple of hours.

2024-11-02 09:17 UTC, markusdent commented on server/src/main/kotlin/eu/dobschal/service/BuildingService.kt
> +        if (building.user != currentUser) {
is it fine to check for the user here?  Or would be user.id check be more safe?

2024-11-02 10:32 UTC, markusdent commented on server/src/main/kotlin/eu/dobschal/service/BuildingService.kt
> +        return SuccessResponseDto("serverSuccess.buildingDestroyed")
Is the success response fine here?

Or do you want to have this as an event?

2024-11-02 20:25 UTC, dobschal requested changes
Nice to see some Markus Code again :)

2024-11-02 20:25 UTC, dobschal commented on server/src/main/kotlin/eu/dobschal/repository/BuildingRepository.kt
> +
❤️

2024-11-02 20:25 UTC, dobschal commented on server/src/main/kotlin/eu/dobschal/service/BuildingService.kt
> +        return SuccessResponseDto("serverSuccess.buildingDestroyed")
@markusdent Yep, need an event here, so that the frontend is updating the map. So need a new EventType too.

The event table is always fetched from the frontend to check if the map or buildings etc. need to be updated.

2024-11-02 20:25 UTC, dobschal commented on server/src/test/kotlin/eu/dobschal/resource/BuildingResourceTest.kt
> +    fun `Destroying own building fails if last available village`() {
Nice!

2024-11-03 09:36 UTC, dobschal approved these changes
Awesome

2024-11-03 09:36 UTC, merged